/*
 * File: leg_convert.c
 *
 * MATLAB Coder version            : 5.6
 * C/C++ source code generated on  : 07-Aug-2025 14:20:57
 */

/* Include Files */
#include "leg_convert.h"
#include <math.h>

/* Function Definitions */
/*
 * LEG_CONVERT
 *     T = LEG_CONVERT(F,Tp,PHI1,PHI4)
 *
 * Arguments    : float F
 *                float Tp
 *                float phi1
 *                float phi4
 *                float T[2]
 * Return Type  : void
 */
void leg_convert(float F, float Tp, float phi1, float phi4, float T[2])
{
  float t102_tmp;
  float t112;
  float t118_tmp;
  float t130_tmp;
  float t141_tmp;
  float t16_tmp;
  float t18_tmp;
  float t33_tmp;
  float t34_tmp;
  float t35_tmp;
  float t36_tmp;
  float t49_tmp;
  float t4_tmp;
  float t50_tmp;
  float t57_tmp;
  float t58_tmp;
  float t59_tmp;
  float t5_tmp;
  float t60_tmp;
  float t61_tmp;
  float t62_tmp;
  float t6_tmp;
  float t7_tmp;
  float t91_tmp;
  /*     This function was generated by the Symbolic Math Toolbox version 9.3.
   */
  /*     2025-12-18 00:22:47 */
  t4_tmp = (float)cos(phi1);
  t5_tmp = (float)cos(phi4);
  t6_tmp = (float)sin(phi1);
  t7_tmp = (float)sin(phi4);
  t16_tmp = t4_tmp * 0.216F;
  t18_tmp = t6_tmp * 0.216F;
  t33_tmp = t4_tmp * 0.108864F;
  t34_tmp = t5_tmp * 0.108864F;
  t35_tmp = t6_tmp * 0.108864F;
  t36_tmp = t7_tmp * 0.108864F;
  t49_tmp = t16_tmp - t5_tmp * 0.216F;
  t50_tmp = t18_tmp - t7_tmp * 0.216F;
  t57_tmp = t33_tmp - t34_tmp;
  t58_tmp = t35_tmp - t36_tmp;
  t59_tmp = t6_tmp * t49_tmp * 0.432F;
  t60_tmp = t7_tmp * t49_tmp * 0.432F;
  t61_tmp = t4_tmp * t50_tmp * 0.432F;
  t62_tmp = t5_tmp * t50_tmp * 0.432F;
  t91_tmp = t49_tmp * t49_tmp + t50_tmp * t50_tmp;
  t102_tmp = 1.0F / ((t34_tmp - t33_tmp) + t91_tmp);
  t49_tmp = t102_tmp * t102_tmp;
  t112 =
      (float)sqrt((t57_tmp * t57_tmp + t58_tmp * t58_tmp) - t91_tmp * t91_tmp);
  t50_tmp = 1.0F / t112;
  t118_tmp = (t36_tmp - t35_tmp) + t112;
  t130_tmp = (float)atan(t102_tmp * t118_tmp) * 2.0F;
  t112 = (float)cos(t130_tmp);
  t130_tmp = (float)sin(t130_tmp);
  t141_tmp = 1.0F / (t49_tmp * (t118_tmp * t118_tmp) + 1.0F);
  t35_tmp = ((t35_tmp + t61_tmp) - t59_tmp) * t49_tmp * t118_tmp +
            t102_tmp * (t33_tmp - t50_tmp *
                                      ((t4_tmp * t58_tmp * 0.217728F -
                                        t6_tmp * t57_tmp * 0.217728F) +
                                       t91_tmp * (t59_tmp - t61_tmp) * 2.0F) /
                                      2.0F);
  t4_tmp = ((t36_tmp + t62_tmp) - t60_tmp) * t49_tmp * t118_tmp +
           t102_tmp * (t34_tmp - t50_tmp *
                                     ((t5_tmp * t58_tmp * 0.217728F -
                                       t7_tmp * t57_tmp * 0.217728F) +
                                      t91_tmp * (t60_tmp - t62_tmp) * 2.0F) /
                                     2.0F);
  t6_tmp = t16_tmp + t112 * 0.252F;
  t33_tmp = t18_tmp + t130_tmp * 0.252F;
  t102_tmp = t112 * t141_tmp;
  t130_tmp *= t141_tmp;
  t49_tmp = t6_tmp * t6_tmp;
  t50_tmp = t33_tmp * t33_tmp + t49_tmp;
  t118_tmp = F * (1.0F / (float)sqrt(t50_tmp));
  t91_tmp = t33_tmp * (1.0F / t49_tmp);
  t112 = Tp * t49_tmp * (1.0F / t50_tmp);
  t50_tmp = t16_tmp - t102_tmp * t35_tmp * 0.504F;
  t49_tmp = t18_tmp - t130_tmp * t35_tmp * 0.504F;
  T[0] =
      t118_tmp * (t33_tmp * t50_tmp * 2.0F - t6_tmp * t49_tmp * 2.0F) / 2.0F +
      t112 * (t50_tmp / t6_tmp + t91_tmp * t49_tmp);
  T[1] = t118_tmp *
             (t102_tmp * t33_tmp * t4_tmp * 1.008F -
              t130_tmp * t6_tmp * t4_tmp * 1.008F) /
             2.0F -
         t112 * ((0.0F - t102_tmp * t4_tmp * 0.504F) / t6_tmp -
                 t91_tmp * (t130_tmp * t4_tmp * 0.504F));
}

/*
 * File trailer for leg_convert.c
 *
 * [EOF]
 */
