/*
 * File: leg_position.c
 *
 * MATLAB Coder version            : 5.6
 * C/C++ source code generated on  : 07-Aug-2025 13:06:59
 */

/* Include Files */
#include "leg_position.h"
#include <math.h>

/*
 * LEG_POSITION
 *     POSITION = LEG_POSITION(PHI1,PHI4)
 *
 * Arguments    : float phi1
 *                float phi4
 *                float position[2]
 * Return Type  : void
 */
void leg_position(float phi1, float phi4, float *l0, float *phi0)
{
    float t12;
    float t13;
    float t14;
    float t15;
    float t2;
    float t3;
    float t4;
    float t5;
    float t6;
    float t8_tmp;

    /*     This function was generated by the Symbolic Math Toolbox version 9.3.
     */
    /*     2025-12-18 00:22:45 */
    t2 = (float)cos(phi1);
    t3 = (float)cos(phi4);
    t4 = (float)sin(phi1);
    t5 = (float)sin(phi4);
    t6 = t2 * 0.216F;
    t8_tmp = t4 * 0.216F;
    t12 = t2 * 0.108864F;
    t13 = t3 * 0.108864F;
    t14 = t4 * 0.108864F;
    t15 = t5 * 0.108864F;
    t4 = t6 - t3 * 0.216F;
    t2 = t8_tmp - t5 * 0.216F;
    t3 = t12 - t13;
    t5 = t14 - t15;
    t2 = t4 * t4 + t2 * t2;
    t2 = (float)atan(1.0F / ((t13 - t12) + t2) *
                     ((t15 - t14) + (float)sqrt((t3 * t3 + t5 * t5) - t2 * t2))) *
         2.0F;
    t4 = t8_tmp + (float)sin(t2) * 0.252F;
    t2 = t6 + (float)cos(t2) * 0.252F;
    *l0 = (float)sqrt(t4 * t4 + t2 * t2);
    *phi0 = atan2(t4, t2);
}

/*
 * File trailer for leg_position.c
 *
 * [EOF]
 */
