/*
 * File: lqr_k_calc.c
 *
 * MATLAB Coder version            : 5.6
 * C/C++ source code generated on  : 07-Aug-2025 14:24:13
 */

/* Include Files */
#include "lqr_k_calc.h"
#include <math.h>

/*
 * LQR_K_CALC
 *     K = LQR_K_CALC(L0)
 *
 * Arguments    : float L0
 *                float K[12]
 * Return Type  : void
 */
void lqr_k_calc(float L0, float K[12])
{
    float t2;
    float t3;
    /*     This function was generated by the Symbolic Math Toolbox version 9.2.
     */
    /*     07-Feb-2023 16:51:43 */
    t2 = L0 * L0;
    t3 = L0 * L0 * L0;
    K[0] = ((L0 * -211.258835F + t2 * 1015.22308F) - t3 * 1817.23499F) + 0.699061513F;
    K[1] = ((L0 * 49.2124557F - t2 * 770.132141F) + t3 * 2896.59814F) + 1.25057209F;
    K[2] = ((L0 * -2.40154243F - t2 * 46.2304802F) + t3 * 141.760757F) + 0.0104762437F;
    K[3] = ((L0 * 1.42831755F - t2 * 12.8770304F) + t3 * 37.7165871F) - 0.00443054922F;
    K[4] = ((L0 * -51.4130325F + t2 * 275.508392F) - t3 * 520.126282F) + 0.200259954F;
    K[5] = ((L0 * 11.4583416F - t2 * 185.907516F) + t3 * 705.607056F) + 0.342208207F;
    K[6] = ((L0 * -64.2741623F + t2 * 377.489716F) - t3 * 802.854309F) - 0.139831617F;
    K[7] = ((L0 * 5.3542552F - t2 * 156.419785F) + t3 * 664.54895F) + 0.791523755F;
    K[8] = ((L0 * -278.325928F + t2 * 1993.41992F) - t3 * 5447.55518F) + 19.6916142F;
    K[9] = ((L0 * 44.8272476F - t2 * 401.21283F) + t3 * 1221.66321F) + 21.4454517F;
    K[10] = ((L0 * -1.78953135F + t2 * 12.3398371F) - t3 * 34.7245293F) + 0.158956423F;
    K[11] = ((L0 * 0.0363001712F + t2 * 0.802958548F) - t3 * 4.63631153F) + 0.156774908F;
}

/*
 * File trailer for lqr_k_calc.c
 *
 * [EOF]
 */