/*
 * File: leg_speed.c
 *
 * MATLAB Coder version            : 5.6
 * C/C++ source code generated on  : 07-Aug-2025 14:17:38
 */

/* Include Files */
#include "leg_speed.h"
#include <math.h>

/* Function Definitions */
/*
 * LEG_SPEED
 *     SPEED = LEG_SPEED(DPHI1,DPHI4,PHI1,PHI4)
 *
 * Arguments    : float dphi1
 *                float dphi4
 *                float phi1
 *                float phi4
 *                float speed[2]
 * Return Type  : void
 */
void leg_speed(float dphi1, float dphi4, float phi1, float phi4, float *d_l0, float *d_phi0)
{
  float t10_tmp;
  float t12_tmp;
  float t2;
  float t21;
  float t22;
  float t23;
  float t24;
  float t29;
  float t3;
  float t30;
  float t33;
  float t34;
  float t35;
  float t36;
  float t37;
  float t38;
  float t4;
  float t5;
  float t51;
  float t59;
  float t60;
  float t64;
  float t66;
  float t73;
  /*     This function was generated by the Symbolic Math Toolbox version 9.3.
   */
  /*     2025-12-18 00:22:46 */
  t2 = (float)cos(phi1);
  t3 = (float)cos(phi4);
  t4 = (float)sin(phi1);
  t5 = (float)sin(phi4);
  t10_tmp = t2 * 0.216F;
  t12_tmp = t4 * 0.216F;
  t21 = t2 * 0.108864F;
  t22 = t3 * 0.108864F;
  t23 = t4 * 0.108864F;
  t24 = t5 * 0.108864F;
  t29 = t10_tmp - t3 * 0.216F;
  t30 = t12_tmp - t5 * 0.216F;
  t33 = t21 - t22;
  t34 = t23 - t24;
  t35 = t4 * t29 * 0.432F;
  t36 = t5 * t29 * 0.432F;
  t37 = t2 * t30 * 0.432F;
  t38 = t3 * t30 * 0.432F;
  t51 = t29 * t29 + t30 * t30;
  t59 = 1.0F / ((t22 - t21) + t51);
  t60 = t59 * t59;
  t64 = (float)sqrt((t33 * t33 + t34 * t34) - t51 * t51);
  t29 = 1.0F / t64;
  t66 = (t24 - t23) + t64;
  t73 = (float)atan(t59 * t66) * 2.0F;
  t30 = (float)cos(t73);
  t64 = (float)sin(t73);
  t73 = 1.0F / (t60 * (t66 * t66) + 1.0F);
  t23 = ((t23 + t37) - t35) * t60 * t66 +
        t59 * (t21 - t29 *
                         ((t2 * t34 * 0.217728F - t4 * t33 * 0.217728F) +
                          t51 * (t35 - t37) * 2.0F) /
                         2.0F);
  t29 = ((t24 + t38) - t36) * t60 * t66 +
        t59 * (t22 - t29 *
                         ((t3 * t34 * 0.217728F - t5 * t33 * 0.217728F) +
                          t51 * (t36 - t38) * 2.0F) /
                         2.0F);
  t4 = t10_tmp + t30 * 0.252F;
  t21 = t12_tmp + t64 * 0.252F;
  t60 = t30 * t73;
  t2 = t60 * t29;
  t73 *= t64;
  t66 = t73 * t29;
  t51 = t4 * t4;
  t29 = t21 * t21 + t51;
  t59 = 1.0F / (float)sqrt(t29);
  t30 = 1.0F / t29;
  t64 = t21 * (1.0F / t51);
  t60 = t10_tmp - t60 * t23 * 0.504F;
  t29 = t12_tmp - t73 * t23 * 0.504F;
  *d_l0 = dphi4 * t59 * (t21 * t2 * 1.008F - t4 * t66 * 1.008F) / 2.0F +
             dphi1 * t59 * (t21 * t60 * 2.0F - t4 * t29 * 2.0F) / 2.0F;
  *d_phi0 =
      -dphi4 * t51 * t30 * ((0.0F - t2 * 0.504F) / t4 - t64 * (t66 * 0.504F)) +
      dphi1 * t51 * t30 * (t60 / t4 + t64 * t29);
}

/*
 * File trailer for leg_speed.c
 *
 * [EOF]
 */
